---
title: "Tomato for Carlos"
output: html_notebook
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, autodep = TRUE)
```

```{r}
library(rstan)
library(rethinking)
library(brms)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
if(file.exists("~/Google Drive/Rdata/carlos.Rdata")) load("~/Google Drive/Rdata/carlos.Rdata")
```

```{r}
tomato <- read.csv("TomatoR2CSHL.csv")
summary(tomato)
```

```{r, results='hide'}
hyp1 <- brm(hyp ~ acs*trt + (trt|species) + (1|shelf),
            prior = c(
              set_prior("normal(20,10)",class="Intercept"),
              set_prior("normal(0,10)",class="b"),
              set_prior("cauchy(0,1)",class="sigma")
            ),
            iter=5000,
            warmup=1500,
            data=tomato)
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r}
hyp2 <- brm(hyp ~ acs*trt + (1|species) + (1|shelf),
            prior = c(
              set_prior("normal(20,10)",class="Intercept"),
              set_prior("normal(0,10)",class="b"),
              set_prior("cauchy(0,1)",class="sigma")
            ),
            iter=5000,
            warmup=1500,
            data=tomato)
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r}
hyp3 <- update(hyp1, formula. = hyp ~ acs*trt + (1|species))
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r}
hyp4 <- update(hyp1, formula. = hyp ~ acs*trt + (1|shelf))
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r}
hyp5 <- update(hyp1, formula. = hyp ~ acs*trt)
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r}
loo(hyp1,hyp2,hyp3,hyp4,hyp5)
```

So we should go with hyp4 (no species effect)
```{r}
summary(hyp4)
plot(hyp4, ask=FALSE)
ranef(hyp4)
```

```{r}
pred.df <- unique(tomato[,c("species","acs","trt")])
head(pred.df)
hyp.prediction <- cbind(pred.df,fitted(hyp4,newdata = pred.df, re_formula = NA))
colnames(hyp.prediction)[6:7] <- c("low95","high95")
head(hyp.prediction)
write.csv(hyp.prediction,file="hyp_accession.csv")
```

```{r}
pl <- ggplot(hyp.prediction,aes(x=acs,y=Estimate,ymin=low95,ymax=high95, fill=trt))
pl <- pl + geom_bar(position="dodge",stat="identity")
pl <- pl + geom_errorbar(position=position_dodge(width=.9), width=0.5)
pl <- pl + facet_wrap( ~ species, ncol=2, scales="free_x")
pl + ggtitle("hypocotyls per accession")
ggsave("hypocotyls_accession.pdf",height=11,width=8.5)
```

```{r, results='hide'}
by(tomato$intleng,tomato$trt,mean)
int1 <- brm(intleng ~ acs*trt + (trt|species) + (1|shelf),
            prior = c(
              set_prior("normal(10,10)",class="Intercept"),
              set_prior("normal(0,20)",class="b"),
              set_prior("cauchy(0,1)",class="sigma")
            ),
            iter=5000,
            warmup=1500,
            data=tomato)
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r}
int2 <- update(int1, formula. = intleng ~ acs*trt + (1|species) + (1|shelf))
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r}
int3 <- update(int2, formula. = intleng ~ acs*trt + (1|species))
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r}
int4 <- update(int3, formula. = intleng ~ acs*trt + (1|shelf))
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r}
int5 <- update(int1, formula. = intleng ~ acs*trt)
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r}
loo(int1,int2,int3,int4,int5)
```

So we should go with int4 (no species effect).  Case could also be made for int5 (no random effects)
```{r}
summary(int4)
plot(int4, ask=FALSE)
ranef(int4)
```

```{r}
intleng.prediction <- cbind(pred.df,fitted(int4,newdata = pred.df, re_formula = NA))
colnames(intleng.prediction)[6:7] <- c("low95","high95")
head(intleng.prediction)
write.csv(intleng.prediction,file="intleng_accession.csv")
```

```{r}
pl <- ggplot(intleng.prediction,aes(x=acs,y=Estimate,ymin=low95,ymax=high95, fill=trt))
pl <- pl + geom_bar(position="dodge",stat="identity")
pl <- pl + geom_errorbar(position=position_dodge(width=.9), width=0.5)
pl <- pl + facet_wrap( ~ species, ncol=2, scales="free_x")
pl + ggtitle("internode")
ggsave("internodes_accession.pdf",height=11,width=8.5)
```

## species level analyses

### hypocotyl

```{r, results='hide'}
hyp6 <- brm(hyp ~ species*trt + (trt|acs) + (1|shelf),
            prior = c(
              set_prior("normal(20,10)",class="Intercept"),
              set_prior("normal(0,10)",class="b"),
              set_prior("cauchy(0,1)",class="sigma")
            ),
            iter=5000,
            warmup=1500,
            data=tomato)
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r, results='hide'}
hyp7 <- update(hyp6, formula. = . ~ species*trt + (1|acs) + (1|shelf) )
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```


```{r, results='hide'}
hyp8 <- update(hyp7, formula. = . ~ species*trt + (1|shelf) )
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r, results='hide'}
hyp9 <- update(hyp7, formula. = . ~ species*trt + (1|acs) )
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r, results='hide'}
hyp10 <- update(hyp7, formula. = . ~ species*trt)
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r}
summary(hyp6)
```

```{r}
summary(hyp7)
```

```{r}
summary(hyp8)
```

```{r}
summary(hyp9)
```

```{r}
summary(hyp10)
```

```{r}
loo(hyp6,hyp7,hyp8,hyp9,hyp10)
```

hyp6, 7 equivalent (no need for trt|acs)
hyp8, 10 much worse (keep acs intercept random effect)
hyp9 a bit worse (some evidenc for shelf effects)

go with hyp7

```{r}
pred.df.species <- unique(tomato[,c("species","trt")])
hyp.species.prediction <- cbind(pred.df.species,fitted(hyp7,newdata = pred.df.species, re_formula = NA))
colnames(hyp.species.prediction)[5:6] <- c("low95","high95")
head(hyp.species.prediction)
write.csv(hyp.species.prediction,file="hyp_species.csv")
```

```{r}
pl <- ggplot(hyp.species.prediction,aes(x=species,y=Estimate,ymin=low95,ymax=high95, fill=trt))
pl <- pl + geom_bar(position="dodge",stat="identity")
pl <- pl + geom_errorbar(position=position_dodge(width=.9), width=0.5)
pl + ggtitle("hypocotyls per species")
ggsave("hypocotyls_species.pdf")
```

### internode

```{r, results='hide'}
int6 <- brm(intleng ~ species*trt + (trt|acs) + (1|shelf),
            prior = c(
              set_prior("normal(20,10)",class="Intercept"),
              set_prior("normal(0,10)",class="b"),
              set_prior("cauchy(0,1)",class="sigma")
            ),
            iter=5000,
            warmup=1500,
            data=tomato)
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r, results='hide'}
int7 <- update(int6, formula. = . ~ species*trt + (1|acs) + (1|shelf) )
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```


```{r, results='hide'}
int8 <- update(int7, formula. = . ~ species*trt + (1|shelf) )
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r, results='hide'}
int9 <- update(int7, formula. = . ~ species*trt + (1|acs) )
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r, results='hide'}
int10 <- update(int7, formula. = . ~ species*trt)
save.image(file="~/Google Drive/Rdata/carlos.Rdata")
```

```{r}
loo(int6,int7,int8,int9,int10)
```

int6 is best

```{r}
int.species.prediction <- cbind(pred.df.species,fitted(int6,newdata = pred.df.species, re_formula = NA))
colnames(int.species.prediction)[5:6] <- c("low95","high95")
head(int.species.prediction)
write.csv(int.species.prediction,file="int_species.csv")
```

```{r}
pl <- ggplot(int.species.prediction,aes(x=species,y=Estimate,ymin=low95,ymax=high95, fill=trt))
pl <- pl + geom_bar(position="dodge",stat="identity")
pl <- pl + geom_errorbar(position=position_dodge(width=.9), width=0.5)
pl + ggtitle("internode per species")
ggsave("internodes_species.pdf")
```